### ISSUE TITLE
Anwell TODOs

### ISSUE THREAD

**Issue by anwell** [grant/go-diagram#2]
- [x] Traverse directories, return nested package->file->struct hierarchy
- [ ] Handle scoping of names, give each type declaration a unique name
- [ ] Go build system
- Roundtripping
    - [x] Creation of new structs
    - [ ] Modification of structs
    - [ ] Safe deletion
    - [ ] Deserialization of structs from client to AST
- [ ] Scoping: Don't assume that all types are unique names
- [ ] Unmarshal client JSON -> server struct
- [x] Multiple names per field
- [ ] Multiple types per field (eg maps kv)
- [ ] Nested directories

Extra
- [ ] Anonymous structs
- [ ] unnamed/unexported fields

**Comment by grant** [comment]
Good work. :+1:
